# Generated by Django 4.0.8 on 2023-03-09 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=20)),
                ('email', models.EmailField(help_text='Enter your mail id', max_length=254, unique=True)),
                ('password', models.CharField(default='null', max_length=30)),
                ('skills', models.CharField(max_length=20)),
                ('secskill', models.CharField(default='null', max_length=20)),
                ('thirdskill', models.CharField(default='null', max_length=20)),
                ('up_for_work', models.CharField(help_text='Are you up for work', max_length=3)),
                ('response_time', models.CharField(max_length=20)),
                ('member_since', models.DateField(auto_now=True)),
                ('Last_delivary', models.DateField(auto_now=True)),
                ('expert_in', models.CharField(max_length=30)),
                ('no_works', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Enter your skills', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your first name', max_length=20)),
                ('email', models.EmailField(help_text='Enter your mail id', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Set the Password', max_length=30)),
                ('professional', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pays.professional')),
            ],
        ),
    ]
