# Generated by Django 4.0.8 on 2023-03-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pays.professional'),
        ),
    ]
