# Generated by Django 4.0.8 on 2023-03-09 11:06

from django.db import migrations, models
import django.db.models.deletion
import pays.models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0002_alter_user_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.ForeignKey(db_constraint=False, default=pays.models.default_prof, on_delete=django.db.models.deletion.SET_DEFAULT, to='pays.professional'),
        ),
    ]
