# Generated by Django 4.0.8 on 2023-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0004_alter_professional_last_delivary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(help_text='Enter your mail id', max_length=254),
        ),
    ]
