# Generated by Django 4.0.8 on 2023-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0005_alter_professional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(help_text='Enter your mail id', max_length=254, unique=True),
        ),
    ]
