# Generated by Django 4.0.8 on 2023-03-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0008_alter_user_otp_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Deadline',
            field=models.DateField(max_length=30),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Negotiated_amount', models.IntegerField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pays.post')),
            ],
        ),
    ]
