# Generated by Django 4.0.8 on 2023-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0009_alter_post_deadline_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Deadline',
            field=models.CharField(max_length=30),
        ),
    ]
