# Generated by Django 4.0.8 on 2023-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0010_alter_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='client_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='agreement',
            name='prof_name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
