# Generated by Django 4.0.8 on 2023-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0011_agreement_client_name_agreement_prof_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
